# Site settings
title: "Typewriter"
description: "So I was feeling nostalgic."
baseurl: /PersonalBlog
url: "http://mnive93.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/mnive93
  - title: "git"
    url: http://github.com/mnive93
  - title: "rss"
    url: /feed.xml
