# Site settings
title: Code Blog
email: mnive93@gmail.com
author: Nivedita Muthusubramanian
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: /PersonalBlog
url: "http://mnive93.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
